# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ProcessingKitSample' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ProcessingKitSample
  pod "ProcessingKit"

  target 'ProcessingKitSampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ProcessingKitSampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
